#if !canImport(ObjectiveC)
import XCTest

extension KeyPathReflectorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyPathReflectorTests = [
        ("testCachedKeyPaths", testCachedKeyPaths),
        ("testNameReflections", testNameReflections),
        ("testUniverseWorks", testUniverseWorks),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KeyPathReflectorTests.__allTests__KeyPathReflectorTests),
    ]
}
#endif
